import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
    color: '#f5f5f5',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    padding: 12,
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#0f0f0f',
  },
  textAreaInput: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    padding: 12,
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#0f0f0f',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  picker: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    backgroundColor: '#0f0f0f',
    color: '#fff',
  },
  errorMessage: {
    backgroundColor: 'rgba(231, 76, 60, 0.1)',
    borderWidth: 1,
    borderColor: '#e74c3c',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 6,
    marginBottom: 16,
  },
  errorText: {
    color: '#e74c3c',
    fontSize: 13,
    fontWeight: '500',
  },
  rowContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  halfInput: {
    flex: 1,
  },
  dateButton: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    padding: 12,
    backgroundColor: '#0f0f0f',
    justifyContent: 'center',
  },
  dateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  cardPickerContainer: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    backgroundColor: '#0f0f0f',
    paddingVertical: 8,
  },
  cardPickerItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  cardPickerItemText: {
    color: '#fff',
    fontSize: 14,
  },
  currencyPickerItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a2a',
  },
  currencyPickerItemSelected: {
    backgroundColor: 'rgba(46, 213, 115, 0.08)',
  },
  currencyPickerItemText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  currencyPickerItemSubtext: {
    color: '#999',
    fontSize: 12,
    marginTop: 4,
  },
  selectedCardContainer: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 6,
    padding: 12,
    backgroundColor: '#1a1a1a',
  },
  selectedCardText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  selectorTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  selectorSubtitle: {
    color: '#9a9a9a',
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  selectedCardBrand: {
    color: '#2ed573',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  fieldHint: {
    color: '#999',
    fontSize: 12,
    marginTop: 8,
    lineHeight: 17,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  modalCloseText: {
    color: '#999',
    fontSize: 24,
    lineHeight: 24,
  },
  modalSectionTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  actionLinkText: {
    color: '#2ed573',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  warningText: {
    color: '#f1c40f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  suggestionCard: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: 'rgba(46, 213, 115, 0.12)',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#2ed573',
    borderWidth: 1,
    borderColor: '#2ed573',
  },
  suggestionTitle: {
    color: '#2ed573',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  suggestionValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  suggestionMeta: {
    color: '#aaa',
    fontSize: 12,
    marginTop: 4,
  },
  suggestionHint: {
    color: '#888',
    fontSize: 11,
    marginTop: 6,
    fontStyle: 'italic',
  },
  currencyPickerCheck: {
    color: '#2ed573',
    fontSize: 16,
    fontWeight: '800',
  },
  submitButton: {
    marginTop: 28,
    marginBottom: 24,
    backgroundColor: '#fff',
    paddingVertical: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#000',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '600',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
});
