@baseUrl = http://localhost:3000
@email = silva@mail.com
@password = teste123!
@phoneNumber = +5512991957161

###############################################################################
### 1️⃣ REGISTRAR NOVO USUÁRIO
###############################################################################

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "João Teste",
  "email": "{{email}}",
  "password": "{{password}}",
  "phoneNumber": "{{phoneNumber}}"
}


###############################################################################
### 2️⃣ CONFIRMAR COM CÓDIGO SMS
###############################################################################

@smsCode = 986580

POST {{baseUrl}}/auth/confirm-sms
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "{{smsCode}}"
}

###############################################################################
### 3️⃣ FAZER LOGIN
###############################################################################

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###############################################################################
### 4️⃣ RENOVAR TOKEN (REFRESH)
###############################################################################

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYTIxZWM4Yi1mY2Q2LTQ1NGUtYmJmNy0wMDhjMjcwOTdlY2YiLCJlbWFpbCI6InNpbHZhQG1haWwuY29tIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NzgwMjk2ODAsImV4cCI6MTc3ODYzNDQ4MH0.zVhnrySPas1qvM6CjHwaD54vC87-7ut59X4tE65dEac

POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###############################################################################
### 5️⃣ REENVIAR CÓDIGO SMS
###############################################################################

POST {{baseUrl}}/auth/resend-confirmation-sms
Content-Type: application/json

{
  "email": "{{email}}"
}

###############################################################################
### 6️⃣ LOGOUT (REVOGA UM REFRESH TOKEN)
###############################################################################

@accessToken = COLE_O_ACCESS_TOKEN_AQUI

POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###############################################################################
### 7️⃣ LOGOUT EM TODOS OS DISPOSITIVOS
###############################################################################

POST {{baseUrl}}/auth/logout-all
Authorization: Bearer {{accessToken}}
Content-Type: application/json
