@baseUrl = http://localhost:3000
@accessToken = seu_token_jwt_aqui

### Teste parsing OFX
POST {{baseUrl}}/statements/test-parse
Content-Type: application/json

{
  "format": "ofx",
  "content": "OFXHEADER:100\nOFXVER:102\nSECURITY:NONE\nENCODING:USASCII\nCHARSET:1252\nCOMPRESSION:NONE\nOLDFILEFMT:N\nNEWFILEFMT:N\nOFXSGML:\n<OFX>\n<SIGNONMSGSRSV1>\n<SONRS>\n<STATUS>\n<CODE>0\n<SEVERITY>INFO\n</STATUS>\n<DTSERVER>20260505101500\n<LANGUAGE>ENG\n</SONRS>\n</SIGNONMSGSRSV1>\n<BANKMSGSRSV1>\n<STMTTRNRS>\n<STATUS>\n<CODE>0\n<SEVERITY>INFO\n</STATUS>\n<STMTRS>\n<CURDEF>BRL\n<BANKTRANLIST>\n<DTSTART>20260401000000\n<DTEND>20260505000000\n<STMTTRN>\n<TRNTYPE>DEBIT\n<DTPOSTED>20260403\n<TRNAMT>-150.50\n<FITID>001\n<NAME>PADARIA DO JOAO\n</STMTTRN>\n<STMTTRN>\n<TRNTYPE>CREDIT\n<DTPOSTED>20260404\n<TRNAMT>5000.00\n<FITID>002\n<NAME>SALARIO\n<MEMO>Salário transferido\n</STMTTRN>\n<STMTTRN>\n<TRNTYPE>DEBIT\n<DTPOSTED>20260405\n<TRNAMT>-250.00\n<FITID>003\n<NAME>CINEMA MULTIPLEX\n</STMTTRN>\n</BANKTRANLIST>\n<LEDGERBAL>\n<BALAMT>10000.00\n<DTASOF>20260505\n</LEDGERBAL>\n</STMTRS>\n</STMTTRNRS>\n</BANKMSGSRSV1>\n</OFX>"
}

### Importar extrato OFX
POST {{baseUrl}}/statements/import
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "format": "ofx",
  "cardId": "card-id-here",
  "content": "OFXHEADER:100\nOFXVER:102\nSECURITY:NONE\nENCODING:USASCII\nCHARSET:1252\nCOMPRESSION:NONE\nOLDFILEFMT:N\nNEWFILEFMT:N\nOFXSGML:\n<OFX>\n<SIGNONMSGSRSV1>\n<SONRS>\n<STATUS>\n<CODE>0\n<SEVERITY>INFO\n</STATUS>\n<DTSERVER>20260505101500\n<LANGUAGE>ENG\n</SONRS>\n</SIGNONMSGSRSV1>\n<BANKMSGSRSV1>\n<STMTTRNRS>\n<STATUS>\n<CODE>0\n<SEVERITY>INFO\n</STATUS>\n<STMTRS>\n<CURDEF>BRL\n<BANKTRANLIST>\n<DTSTART>20260401000000\n<DTEND>20260505000000\n<STMTTRN>\n<TRNTYPE>DEBIT\n<DTPOSTED>20260403\n<TRNAMT>-150.50\n<FITID>001\n<NAME>PADARIA DO JOAO\n</STMTTRN>\n</BANKTRANLIST>\n<LEDGERBAL>\n<BALAMT>10000.00\n<DTASOF>20260505\n</LEDGERBAL>\n</STMTRS>\n</STMTTRNRS>\n</BANKMSGSRSV1>\n</OFX>"
}
