import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#000',
  },
  backButton: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
  },
  headerSpacer: {
    width: 50,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    padding: 16,
    gap: 16,
  },
  heroCard: {
    flexDirection: 'row',
    gap: 14,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  heroIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563eb',
  },
  heroText: {
    flex: 1,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  heroDescription: {
    marginTop: 6,
    color: '#94a3b8',
    lineHeight: 20,
    fontSize: 13,
  },
  warningCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#3f1d1d',
    borderWidth: 1,
    borderColor: '#6b2a2a',
  },
  warningTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  warningText: {
    marginTop: 6,
    color: '#fecaca',
    lineHeight: 19,
    fontSize: 13,
  },
  inputCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  inputLabel: {
    color: '#cbd5e1',
    fontSize: 13,
    marginBottom: 10,
    fontWeight: '600',
  },
  input: {
    borderRadius: 14,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#334155',
    color: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  sessionCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  sessionRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  sessionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  sessionTextBlock: {
    flex: 1,
  },
  sessionTitle: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  sessionDescription: {
    marginTop: 4,
    color: '#94a3b8',
    fontSize: 13,
    lineHeight: 18,
  },
  actionGrid: {
    marginTop: 16,
    gap: 10,
  },
  primaryButton: {
    borderRadius: 14,
    backgroundColor: '#0f766e',
    paddingVertical: 13,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  secondaryButton: {
    borderRadius: 14,
    backgroundColor: '#e2e8f0',
    paddingVertical: 13,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  secondaryButtonText: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 14,
  },
  dangerButton: {
    borderRadius: 14,
    backgroundColor: '#b91c1c',
    paddingVertical: 13,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  dangerButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  listCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  listTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  emptyText: {
    color: '#94a3b8',
    fontSize: 13,
    lineHeight: 18,
  },
  backupRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#1f2937',
  },
  backupDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#0f766e',
    marginTop: 4,
  },
  backupTextBlock: {
    flex: 1,
  },
  backupName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  backupMeta: {
    marginTop: 3,
    color: '#94a3b8',
    fontSize: 12,
  },
});
