import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  heroBackgroundTop: {
    position: 'absolute',
    top: -100,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(46, 213, 115, 0.12)',
  },
  heroBackgroundBottom: {
    position: 'absolute',
    bottom: -120,
    left: -100,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(59, 130, 246, 0.10)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  headerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#2ed573',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  headerTextBlock: {
    flex: 1,
  },
  kicker: {
    fontSize: 12,
    color: '#2ed573',
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  title: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: '#fff',
  },
  scrollContent: {
    paddingBottom: 28,
  },
  formCard: {
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  sectionLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 14,
  },
  goalContextCard: {
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  goalContextTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
  },
  goalContextSubtitle: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 14,
  },
  goalContextMetricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  goalContextMetric: {
    flex: 1,
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#222',
  },
  goalContextProgressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#0f0f0f',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 12,
    color: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  halfWidth: {
    flex: 1,
  },
  formHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 14,
  },
  formHint: {
    flex: 1,
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  detailToggle: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(46, 213, 115, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(46, 213, 115, 0.22)',
  },
  detailToggleText: {
    color: '#2ed573',
    fontSize: 11,
    fontWeight: '800',
  },
  resultCard: {
    backgroundColor: '#101412',
    borderWidth: 1,
    borderColor: 'rgba(46, 213, 115, 0.25)',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  resultTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  resultLabel: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
  },
  resultValue: {
    color: '#fff',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
  },
  resultBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(46, 213, 115, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(46, 213, 115, 0.24)',
  },
  resultBadgeText: {
    color: '#2ed573',
    fontSize: 11,
    fontWeight: '800',
  },
  resultMetricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#222',
  },
  metricLabel: {
    color: '#9ca3af',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  metricValue: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  progressBlock: {
    gap: 8,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressLabel: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  progressValue: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '700',
  },
  progressTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: '#1b1b1b',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#2ed573',
  },
  detailsCard: {
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#1f1f1f',
  },
  detailKey: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  detailValue: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  detailValuePositive: {
    color: '#2ed573',
    fontSize: 12,
    fontWeight: '800',
  },
  timelineCard: {
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  timelineList: {
    marginTop: 4,
  },
  timelineSummary: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2ed573',
    marginRight: 12,
  },
  timelineTextBlock: {
    flex: 1,
  },
  timelineTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  timelineSubtitle: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
  },
  emptyStateText: {
    color: '#9ca3af',
    fontSize: 13,
    lineHeight: 18,
  },
  warningCard: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.30)',
    borderRadius: 16,
    padding: 14,
    marginBottom: 20,
  },
  warningText: {
    color: '#fbbf24',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
});
